// SPDX-License-Identifier: Apache-2.0
//
// What a component IS, as opposed to what it looks like.
//
// ── The gap ─────────────────────────────────────────────────────────────────
//
// The component tree is a purely visual object. A knob is a rectangle that
// draws an arc and responds to drags; nothing in it says "this is a control
// called Gain, currently at -6.0 dB, whose value you may change". So a producer
// using a screen reader gets silence, and a plugin generated by this SDK is
// unusable without sight.
//
// The keyboard half of this landed first -- every control is reachable by Tab
// and operable by arrow keys, which was itself a total barrier -- but a control
// you can operate and cannot hear is still not usable.
//
// ── What this file is, and what it is not ──────────────────────────────────
//
// The vocabulary only: a role, a name, a value and a range. Split from
// accessibility.h so Component can declare accessibleInfo() without including
// the traversal that walks Components -- the circular include that otherwise
// forces the whole thing into component.h.
//
// This file on its own is not a screen reader integration -- it is what a
// bridge READS. gfx/uia_win32.h is the Windows bridge and is verified against a
// real UI Automation client; macOS has none yet and the map carries that as a
// real gap. So on Windows a reader hears a plugin built with this, and on macOS
// it does not.
//
// (This paragraph said "nothing here reaches UI Automation" until the Windows
// bridge landed one commit later. A header comment that describes a limitation
// is a claim with an expiry date, and this one is dated deliberately.)
//
// ── Why roles are a small closed set ───────────────────────────────────────
//
// Every platform has its own vocabulary and they do not agree. A closed enum
// that each bridge maps into its own platform's names is the only arrangement
// where adding a second platform cannot change what the first one says.
#pragma once

#include <string>

#include "geometry.h"

namespace sonore {
namespace gfx {

/**
 * What kind of thing a component is.
 *
 * Deliberately short. Every entry has an obvious equivalent in UI Automation
 * AND in NSAccessibility, which is the test for whether a role belongs: one
 * invented for us would be one no screen reader knows how to announce.
 */
enum class AccessibleRole {
  /** Not described. The default, and right for a layout container that exists
   *  only to position things. */
  Unknown,
  Group,
  Window,
  Dialog,
  Button,
  ToggleButton,
  Slider,
  Label,
  TextField,
  ComboBox,
  List,
  ListItem,
  /** A list with columns. Distinct from List because every platform has a
   *  separate name for it and a reader says different things: a List is read
   *  as "item N of M", a Table as a row with named cells. */
  Table,
  ScrollBar,
  ProgressBar,
  /** A piano keyboard. No platform has this one; a bridge maps it to Group and
   *  does NOT enumerate its keys -- 128 list items nobody wants read out. */
  MusicalKeyboard,
};

inline const char* accessibleRoleName(AccessibleRole role) {
  switch (role) {
    case AccessibleRole::Group: return "group";
    case AccessibleRole::Window: return "window";
    case AccessibleRole::Dialog: return "dialog";
    case AccessibleRole::Button: return "button";
    case AccessibleRole::ToggleButton: return "toggle button";
    case AccessibleRole::Slider: return "slider";
    case AccessibleRole::Label: return "label";
    case AccessibleRole::TextField: return "text field";
    case AccessibleRole::ComboBox: return "combo box";
    case AccessibleRole::List: return "list";
    case AccessibleRole::ListItem: return "list item";
    case AccessibleRole::Table: return "table";
    case AccessibleRole::ScrollBar: return "scroll bar";
    case AccessibleRole::ProgressBar: return "progress bar";
    case AccessibleRole::MusicalKeyboard: return "musical keyboard";
    case AccessibleRole::Unknown: break;
  }
  return "unknown";
}

/**
 * Everything a screen reader would want about one component.
 *
 * Built on demand rather than kept as state: the value of a knob is already in
 * the knob, and a second copy updated by a callback is a second copy that can
 * be stale at exactly the moment somebody asks.
 */
struct AccessibleInfo {
  AccessibleRole role = AccessibleRole::Unknown;
  /** What it IS -- "Gain". Not what it reads. */
  std::string name;
  /** What it READS -- "-6.0 dB". The same text drawn on screen, because a
   *  reader announcing a different number from the displayed one is worse than
   *  one announcing nothing. */
  std::string value;
  /** Longer help, for a control whose name does not explain it. */
  std::string description;

  bool focusable = false;
  bool focused = false;
  bool enabled = true;

  /** For a ranged control, so a bridge can offer the platform's own range
   *  interface -- which is what lets a reader say "40 percent" and lets
   *  assistive software set a value directly rather than synthesising drags. */
  bool hasRange = false;
  double minValue = 0.0;
  double maxValue = 1.0;
  double currentValue = 0.0;

  /** In the ROOT's coordinates, which is what answers "what is at this
   *  position". Filled in by the traversal, not by the component: a component
   *  knows where it is inside its parent and nothing more. */
  Rect bounds;
};

} // namespace gfx
} // namespace sonore
